### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by yann510** [swimlane/ng2d3#44]
I know this is in your coming soon features, but I'm still adding it as the other coming soon features are open issues. I'm also interested to know if someone is already working on this? I would surely like to give a hand as this feature is a must have for responsive components!

**Comment by amcdnl** [comment]
@yann510 - We haven't started working on it yet. 

@marjan-georgiev can you point him in the direction to go about implementing this?

**Comment by marjan-georgiev** [comment]
There is currently a way to achieve a sort of responsiveness by changing the view parameter of the components to the new dimensions on parent resize. The charts are smart enough to adapt to the new dimensions, but there is room for a lot of improvement. 

Some of the charts still need work on their layout (Advanced Pie Chart being one of them), as well as all of the charts that have legends.

We are open to any ideas and PR's are welcome.

**Comment by yann510** [comment]
@marjan-georgiev Do you guys have a slack or something ? I have some questions, which I believe would spam this issue.

**Comment by marjan-georgiev** [comment]
@yann510 we have a gitter channel: https://gitter.im/swimlane/ng2d3

**Comment by marjan-georgiev** [comment]
@yann510 Refactored the code in this commit:
https://github.com/swimlane/ng2d3/commit/7686e793a07cfe1914caeb82d1cc8f015ac5c7bd

I added unsubscribe on chart destroy, as the subscriptions were never being cancelled.

Also modified the behavior:
- If the chart has the view input property set, then the dimensions come from the input property
- If the chart does not have the input property set, the dimensions will come from it's parent container

This was added so that you can still manually override the width/height of the chart, in case you don't want it to fit the parent container.

There is one last thing that needs to be added, but I will open a new issue for it. Sometimes the parent container can be resized without resizing the window. In this case, window.onResize will not fire. We will need to add a manual listener on the charts that can trigger the update from outside.

**Comment by yann510** [comment]
Awesome !
Some very important details I didn't think about. 
Thanks for working with me on this one, definitely looking forward to contributing more.

**Comment by mailok** [comment]
Hi!!, how to update manually??
