### ISSUE TITLE
Date values not having a friendly display (as in the demo)

### ISSUE THREAD

**Issue by yann510** [swimlane/ng2d3#45]
Currently trying to reproduce the area-chart from the demo and with the same options and data passed to the table I'm getting this for the dates:
![image](https://cloud.githubusercontent.com/assets/6068943/19085599/dbea50a2-8a38-11e6-997e-bd186f87d430.png)

I'm also wondering if the epoch is supported in this current version?

**Comment by marjan-georgiev** [comment]
Did you copy the data from the sidebar in the demo page? The dates there get converted to string for the JSON representation. In order to get a time scale on the line and area charts, you need to use date objects. If you use strings, you get an ordinal scale.

There's an argument here for detecting whether the string is a representation of a date and converting it internally, but I believe this should be handled outside the charts.

Take a look at this plunkr for an example. I convert the strings into date objects in the constructor in app.ts: https://plnkr.co/edit/HOXr8K?p=preview

**Comment by yann510** [comment]
> There's an argument here for detecting whether the string is a representation of a date and converting it internally, but I believe this should be handled outside the charts.

@marjan-georgiev can you explain why you believe this should be handle outside the charts? I believe many charts do rely on dates/time ?

**Comment by marjan-georgiev** [comment]
Sure. I think it is easier to do some minor wrangling and give the chart precise, formatted data, than have the chart guess whether you want it to treat your strings as dates or actual strings.

- What if you wanted those values to be treated as strings? 
- What if you had the dates in a different format - should we try to parse any possible date format out there?
- What if you didn't have strings, but integers - do we try to parse them as dates too?
 
These are all decisions that the user needs to make, not the chart.

I do think we should make assumptions when applicable in order to cut on configuration, but not here.

**Comment by yann510** [comment]
How about having an option for the x axis where you could specify it's type?
For example:
`[xAxisType]="dateEpoch"`

The xAxisType could of course be an enum specifying the possible types.
I think this would solve all the points you've mentioned and it remove the need from the user to parse the dates. 
What do you think?

**Comment by vforvasquez** [comment]
Just a heads up if you try to use the code in the constructor you will get a "Supplied parameters do not match any signature of call target." error.

**Comment by vforvasquez** [comment]
Just a heads up if you use the code from the plunkr you get a "Type 'Date' is not assignable to type 'string'." warning.

**Comment by Moulde** [comment]
@yann510 I also think this is something the chart should handle. But i also agree with @marjan-georgiev that the chart should not try to guess what the data is, so i like your suggestion about specifying xAxisType.

**Comment by Moulde** [comment]
@marjan-georgiev Parsing integers as a dates is pretty normal in javascript no? (Im thinking specifically about unix epoch).
